spring:
  application:
    name: user-service

server.port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://center.eureka.server:9000/eureka/

# 关闭 actuator 的安全认证
management.security.enabled: false

# 开启消息跟踪
spring.cloud.bus.trace.enabled: true

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

spring.zipkin:
  base-url: http://zipkin-server:9103