spring.application.name: gateway-zuul
server.port: 9102

# zuul默认配置方式：http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**
# 默认就是如下配置
# zuul.routes:
#  api-a.path: /user-service/**
#  api-a.serviceId: USER-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://center.eureka.server:9000/eureka/

#是否开启重试功能
zuul.retryable: true
ribbon:
  MaxAutoRetries: 2 #对当前服务的重试次数
  MaxAutoRetriesNextServer: 0 #切换相同Server的次数
