spring:
  application:
    name: center.eureka.server

server.port: 9000

eureka:
  instance:
    hostname: center.eureka.server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://center.eureka.server:9000/eureka/